# ClearLagg configuration file

# Please Don't Edit configuration ver
config-version: 3

# Time in seconds between automatic clears
clear-interval: 300

# Time interval in seconds for countdown message broadcast
broadcast-interval: 15

# World-specific settings
worlds:
  world:
    enable-auto-clear: true
  world_nether:
    enable-auto-clear: true
  world_the_end:
    enable-auto-clear: true

# Player notifications
notify-players:
  enable: true
  message: "All dropped items will be cleared in 299 seconds!"
  countdown: 299

# Messages
clear-message: "§aGarbage collected correctly."
warning-message: "§cPicking up trash in {time}..."
broadcast-message: "§bThe items will be deleted in {time} seconds."
