name: PHP-CS-Fixer

on:
  pull_request:
  workflows_dispatch:

permissions:
  contents: write

jobs:
  fix:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Install PHP-CS-Fixer
      run: |
        wget https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/download/v3.64.0/php-cs-fixer.phar -O /usr/local/bin/php-cs-fixer
        chmod +x /usr/local/bin/php-cs-fixer

    - name: Run PHP-CS-Fixer and Fix Code
      run: |
        php-cs-fixer fix --allow-risky=yes --quiet
        rm .php-cs-fixer.cache

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions[bot]@github.com'
        git add .
        git commit -m "Apply PHP-CS-Fixer changes"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
